apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: myapp-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: This is an operator to ddeply Applications
  displayName: My App Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - app
  links:
  - name: Myapp Operator
    url: https://myapp-operator.domain
  maintainers:
  - email: jsa400@gmail.com
    name: jsa400
  maturity: alpha
  provider:
    name: jsa4000
  version: 0.0.0
