apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: 1.3.0
  config:
    domain:
      example.com: ""
    istio:
      local-gateway.knative-serving.knative-local-gateway: istio-ingressgateway.istio-system.svc.cluster.local