apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: app
spec:
  crossplane:
    version: ">=v1.5"
  dependsOn:
  - provider: crossplane/provider-kubernetes
    version: ">=v0.3.0"
